"""empty message

Revision ID: 2209070e7018
Revises: b4b79b976fbf
Create Date: 2019-09-19 15:27:45.607125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2209070e7018'
down_revision = 'b4b79b976fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fio', sa.TEXT(length=128), nullable=True))
    # ### end Alembic commands ###
