"""empty message

Revision ID: 4dbc0c41baca
Revises: bfdc74116c5e
Create Date: 2019-08-24 23:46:32.336285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbc0c41baca'
down_revision = 'bfdc74116c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('position', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_location_position'), 'location', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_position'), table_name='location')
    op.drop_column('location', 'position')
    # ### end Alembic commands ###
