MIN_SIZE_DATABASE = 1
MAX_SIZE_DATABASE = 1000

YOUNGEST_VET = 25
OLDEST_VET = 60

LOWEST_CABINET = 1
UPPEST_CABINET = 500

LOWEST_COST = 1000
MOST_COST = 10000

LOWEST_DURATION = 5
MOST_DURATION = 30

YOUNGEST_ANIMAL = 1
OLDEST_ANIMAL = 20

LOWEST_CATEGORY = 1
HIGHEST_CATEGORY = 3

MIN_KINDS = 1
MAX_KINDS = 25

IS_HOSPITALIZATION = "Требуется"
NOT_HOSPITALIZATION = "Не требуется"

NOT_NEED_OPERATION = "Не требуется"
NEED_OPERATION = "Требуется"

LITTLE_SEVERITY_DISEASE = "Легкая"
MIDDLE_SEVERITY_DISEASE = "Средняя"
HIGH_SEVERITY_DISEASE = "Тяжелая"

MIN_SEVERITY = 1
MAX_SEVERITY = 3

FIRST_DATE = [2010, 1, 11]
LAST_DATE = [2021, 9, 18]